[General]
# Which display server should be used.
# Valid values are: x11, x11-user, wayland. Wayland support is experimental
DisplayServer=wayland

[Theme]
# Current theme name
Current=where_is_my_sddm_theme